import os
import cv2


BGR_WHITE = (255, 255, 255)
BGR_BLACK = (0, 0, 0)
BGR_RED = (0, 0, 255)
BGR_GREEN = (0, 255, 0)
BGR_BLUE = (255, 0, 0)
BGCOLOR = 'white'

GAMEFILE = os.path.dirname(__file__)
IMG_FILE = "test12.png"
TEXT_FILE = "data.pdf"
SETTINGS_FILE = "settings.pdf"
GRAYIMG_FILE = "test12gray.png"
INVERT_GRAYIMG_FILE = "test12grayinvert.png"
NUMBER_LIST = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
TITLE = "Incucount"
WIDTH = 700
HEIGHT = 480
DETECTION_METHOD = cv2.HOUGH_GRADIENT
SETTINGS = {"thresh": 1,
            "camnum": 2,
            "circlecertainty": 3,
            "maxsize": 4,
            "minsize": 5,
            "imgtype": 6}

GRAY_CAN_WIDTH = 225
GRAY_CAN_HEIGHT = 180
CAN_WIDTH = 450
CAN_HEIGHT = 370

STORESETTINGSBUTTON_X = WIDTH-175
STORESETTINGSBUTTON_Y = 30
STORESETTINGSBUTTON_WIDTH = 12
THRESHBUTTON_X = WIDTH-235
THRESHBUTTON_Y = STORESETTINGSBUTTON_Y+30
THRESHBUTTON_WIDTH = 12
THRESHINPUT_X = WIDTH-135
THRESHINPUT_Y = THRESHBUTTON_Y+4
THRESHINPUT_WIDTH = 20
THRESH_X = 465
THRESH_Y = 250
CAMNUMBUTTON_X = THRESHBUTTON_X
CAMNUMBUTTON_Y = THRESHBUTTON_Y+30
CAMNUMBUTTON_WIDTH = THRESHBUTTON_WIDTH
CAMINPUT_X = WIDTH-135
CAMINPUT_Y = CAMNUMBUTTON_Y+4
CAMINPUT_WIDTH = 20
CAMNUM_X = THRESH_X
CAMNUM_Y = THRESH_Y+20
CIRCLECERTAINTYBUTTON_X = THRESHBUTTON_X
CIRCLECERTAINTYBUTTON_Y = CAMNUMBUTTON_Y+30
CIRCLECERTAINTYBUTTON_WIDTH = THRESHBUTTON_WIDTH
CIRCLECERTAINTYINPUT_X = WIDTH-135
CIRCLECERTAINTYINPUT_Y = CIRCLECERTAINTYBUTTON_Y+4
CIRCLECERTAINTYINPUT_WIDTH = 20
CIRCLECERTAINTY_X = THRESH_X
CIRCLECERTAINTY_Y = CAMNUM_Y+20
MAXSIZEBUTTON_X = THRESHBUTTON_X
MAXSIZEBUTTON_Y = CIRCLECERTAINTYBUTTON_Y+30
MAXSIZEBUTTON_WIDTH = THRESHBUTTON_WIDTH
MAXSIZEINPUT_X = WIDTH-135
MAXSIZEINPUT_Y = MAXSIZEBUTTON_Y+4
MAXSIZEINPUT_WIDTH = 20
MAXSIZE_X = THRESH_X
MAXSIZE_Y = CIRCLECERTAINTY_Y+20
MINSIZEBUTTON_X = THRESHBUTTON_X
MINSIZEBUTTON_Y = MAXSIZEBUTTON_Y+30
MINSIZEBUTTON_WIDTH = THRESHBUTTON_WIDTH
MINSIZEINPUT_X = WIDTH-135
MINSIZEINPUT_Y = MINSIZEBUTTON_Y+4
MINSIZEINPUT_WIDTH = 20
MINSIZE_X = THRESH_X
MINSIZE_Y = MAXSIZE_Y+20
IMGTYPE_BUTTON_X = THRESHBUTTON_X
IMGTYPE_BUTTON_Y = MINSIZEBUTTON_Y+30
IMGTYPEBUTTON_WIDTH = THRESHBUTTON_WIDTH+5
IMGTYPE_INPUT_X = WIDTH-98
IMGTYPE_INPUT_Y = IMGTYPE_BUTTON_Y-2
IMGTYPE_X = THRESH_X
IMGTYPE_Y = MINSIZE_Y+20
COLONYCOUNT_X = THRESH_X
COLONYCOUNT_Y = IMGTYPE_Y+20
IMGCAN_X = 0
IMGCAN_Y = HEIGHT-CAN_HEIGHT
